{{- $prefix := printf "%s." .Requirements.cluster.project }}
{{- $rootDomain := trimPrefix $prefix .Requirements.ingress.domain }}
sso-operator:
  dex:
    grpcHost: "dex.jx"
dex:
  imageRepo: pmuir/dex
  tag: wip10
  domain: "dex-jx.{{ $rootDomain }}"
  connectors:
    cloudbees:
      config:
        type: cloudbees
        name: CloudBees
        clientID: "{{ .Parameters.dashboardAuthID }}"
        clientSecret: "{{ .Parameters.dashboardAuthSecret }}"
        issuer: https://cloudbees-development.auth0.com/
